apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
  labels:
    app.kubernetes.io/name: fastapi-traefik-datascientest-project
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/environment: prod
    app.kubernetes.io/managed-by: github-actions
data:
  ENVIRONMENT: "production"
  DOMAIN: "api.example.com"
  PROJECT_NAME: "FastAPI Project Production"
  FIRST_SUPERUSER: "admin@example.com"
  BACKEND_CORS_ORIGINS: "https://app.example.com,https://api.example.com"
  POSTGRES_SERVER: "db-prod"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app"
  POSTGRES_USER: "postgres"
