apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
data:
  # Geändert von "production" auf "local", um Pydantic-Validierung zu erfüllen
  ENVIRONMENT: "local"
  DOMAIN: "localhost"
  
  # Neue Pflichtfelder für das Backend
  PROJECT_NAME: "FastAPI Project Prod"
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "fastapi_devops_26"
  
  # CORS Einstellungen (Ports für Traefik 8080 und Port-Forwarding 8081 ergänzt)
  BACKEND_CORS_ORIGINS: "http://localhost:8080,http://localhost:8081,http://localhost:8000,http://localhost,http://localhost:50025"
  
  # Datenbank-Verbindung (Das Passwort wurde entfernt, da es jetzt im Secret steht!)
  POSTGRES_SERVER: "db-prod"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app"
  POSTGRES_USER: "postgres"