apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: prod
  labels:
    app.kubernetes.io/name: fastapi-traefik-datascientest-project
    app.kubernetes.io/component: backend
    app.kubernetes.io/environment: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: prod
  labels:
    app.kubernetes.io/name: fastapi-traefik-datascientest-project
    app.kubernetes.io/component: frontend
    app.kubernetes.io/environment: prod
