[fastapivm_test]
# Direkte interne IP der Test-VM
10.10.10.51 ansible_user=ipatsaf

[fastapivm_test:vars]
# Optimierte SSH-Parameter für die interne Kommunikation
# Wir nutzen SSH-Keys (empfohlen) statt Passwörter.
# Falls kein Key vorhanden ist, muss "sshpass" auf dem Host installiert sein.
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'