[fastapivm_test]
# Die NEUE IP der VM 104
10.10.10.51 ansible_user=ipatsaf ansible_ssh_private_key_file=~/.ssh/id_rsa

[fastapivm_test:vars]
# Routing via Jump-Host (ProxyJump)
# ForwardAgent=yes reicht deinen Mac-Key durch den Tunnel zur Ziel-VM
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ProxyJump=ipatsaf@62.210.89.4'